### ISSUE TITLE
Environement not working with docker-compose

### ISSUE THREAD

**Issue by Soullivaneuh** [phpmyadmin/docker#10]
With the following `docker-compose.yml` file:

```yml
mysql:
  image: mysql
  volumes_from:
    - data
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

pma:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql:db
  ports:
    - '8080:8080'
  environment:
    PMA_USER: root
    PMA_PASSWORD: ''
```

If I dump the `$_ENV` variable from `config.inc.php`, I get an empty array.

Did I something wrong?
