### ISSUE TITLE
Config simply not working

### ISSUE THREAD

**Issue by k2xl** [phpmyadmin/docker#100]
```
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    networks:
      - web_server
    links:
      - mysql:db
    ports:
      - "8080:80"
    volumes:
      - ./config/config.inc.php:/etc/phpmyadmin/config.user.inc.php
```

The config simply does not get read.

config.inc.php:
```
<?php
$cfg['MaxNavigationItems'] = 200;
$cfg['ShowDatabasesNavigationAsTree']=false;
?>
```
