### ISSUE TITLE
Trouble with "Usage with docker-compose and arbitrary server"

### ISSUE THREAD

**Issue by gavinkalika** [phpmyadmin/docker#103]
Ran docker-compose up
Navigated to http://localhost:8080/index.php
Entered  my local mysql server creds and I keep getting the follow:

> #2002 - Connection refused &mdash; The server is not responding (or the local server's socket is not correctly configured).

Any advice? new to docker

**Comment by reissr** [comment]
I'm having the same issue.. subscribing

**Comment by gavinkalika** [comment]
@nijel please?

**Comment by rotemreiss** [comment]
I solved the problem on my installation - in my case it was a bad db host name (although it worked and stopped working for some reason).

@gavinkalika can you share your docker-compose yml here so we'll try to help you?

**Comment by tommasosotte** [comment]
I had the same problem. I solved it by reloading docker (I did a reboot of the entire system).
This is my `docker-compose.yml` and it works for a **webserver + DB+ PMA** combo. I'll leave it here for future reference.
```
    webserver:
        ...
        links:
              - dbtest
        networks:
              - front
         ...
    dbtest:
        ...
        networks:
            - front
            - back
        ...
        environment:
            MYSQL_ROOT_PASSWORD: "dbpassword"
    pma:
        ...
        links:
            - dbtest
        networks:
            - back
        environment:
            MYSQL_ROOT_PASSWORD: "dbpassword"
            PMA_HOST: "dbtest"
networks:
    front:
    back:
```
