### ISSUE TITLE
docker question

### ISSUE THREAD

**Issue by gavinkalika** [phpmyadmin/docker#104]
Below is my docker-compose.yml

I am having trouble editing the project files on my host machine. Could you please point me in right direction

```
mysql:
  image: mysql
  container_name: mysql
#   volumes_from:
#     - data
  environment:
    MYSQL_ROOT_PASSWORD: 'password'
    MYSQL_USER: 'root'


pma:
  container_name: pma
  image: phpmyadmin/phpmyadmin
  links:
    - mysql:db
  ports:
    - '8080:80' #host:container
  environment:
    # PMA_USER: root
    # PMA_PASSWORD: 'password'
   volume: ./docker/src/www:/www/
    #  - ./docker/src/www:/www/
    #  - /sessions

```

**Comment by nijel** [comment]
Shouldn't it be [volumes](https://docs.docker.com/compose/compose-file/#/volumes-volumedriver) (instead of volume)? Also indentation seems to be wrong in your case.

**Comment by gavinkalika** [comment]
```
mysql:
  image: mysql
  container_name: mysql
#   volumes_from:
#     - data
  environment:
    MYSQL_ROOT_PASSWORD: 'password'
    MYSQL_USER: 'root'


pma:
  container_name: pma
  image: phpmyadmin/phpmyadmin
  links:
    - mysql:db
  ports:
    - '8080:80' #host:container
  #  volumes: 
    #  - /Users/gavin/vagrantstuff/spacejam/data/spacejam/docker/src/www/:/www/
  environment:
    # PMA_USER: root
    # PMA_PASSWORD: 'password'
  volumes: 
   - /Users/gavin/vagrantstuff/spacejam/data/spacejam/docker/src/www/:/www/
    #  - ./docker/src/www:/www/
    #  - /sessions
```

**Comment by gavinkalika** [comment]
nada.

i get the following "contains an invalid type, it should be an object, or an array"

**Comment by nijel** [comment]
Seems like one space is missing there (not sure if that's problem, but it's different than the other lines).

PS: What version of docker-compose are you using?

**Comment by gavinkalika** [comment]
docker-compose version -> docker-compose version 1.9.0, build 258538

changed up my docker-compose yaml to 
```

mysql:
  image: mysql
  container_name: mysql
  environment:
    MYSQL_ROOT_PASSWORD: 'password'
    MYSQL_USER: 'root'


pma:
  container_name: pma
  image: phpmyadmin/phpmyadmin
  links:
    - mysql:db
  ports:
    - '8080:80' #host:container
  volumes: 
    - "./docker/src/www/:/www/"


```

I now get a 403 Forbidden
