### ISSUE TITLE
404 Not Found Nginx error

### ISSUE THREAD

**Issue by swamyuma** [phpmyadmin/docker#130]
I am getting a `404 Not Found nginx` error when I visit `http://<host-IP:8181/phpmyadmin` with the following lines in a `docker-compose.yml`

```yml
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - frontend
    ports:
      - 8181:80
    depends_on:
      - db
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ***
      PMA_HOST: mysql
      PMA_PORT: 3306
    volumes:
      - /sessions
```
