### ISSUE TITLE
phpMyAdmin can not connect to MySQL when user "REQUIRE SSL"

### ISSUE THREAD

**Issue by p1t3r** [phpmyadmin/docker#142]
I am trying to establish a connection to MySQL database using certificate. The MySQL server is running on the same host and is not dockerized.
User is configured for all hosts (%) with password and "require ssl" option. He has access SELECT to all databases.

When using mysql client:
`$ mysql -utest0 -p --ssl-ca=./ca-cert.pem --ssl-cert=./public.pem --ssl-key=./private.pem -hsrvdb.com`
either from the server itself or from an external host the connection is successful.
But when trying to connect through phpmyadmin I get an error:
`" #1045 - Access denied for user 'test0'@'myhost.com' (using password: YES)"`
On the other hand, if the option "require ssl" is not enabled the connection from phpmyadmin is successful.

Version of phpmyadmin: 4.7
Version of mysql: 5.5.58

Content of pma.yaml:
```
version: "3"

services:
  pma:
    image: phpmyadmin/phpmyadmin:4.7
    restart: unless-stopped
    volumes:
      - ./pma/etc/phpmyadmin:/etc/phpmyadmin
    environment:
      PMA_HOST: "srvdb.com"
    ports:
      - "8080:80"
    networks:
      - net0

networks:
  net0:
    driver: bridge
```

Content of /etc/phpmyadmin/config.user.inc.php:
```
<?php
/* Encrypted connection to DB */
$cfg['Servers'][$i]['ssl'] = true;
$cfg['Servers'][$i]['ssl_ca'] = '/etc/phpmyadmin/ca-cert.pem';
$cfg['Servers'][$i]['ssl_cert'] = '/etc/phpmyadmin/public.pem';
$cfg['Servers'][$i]['ssl_key'] = '/etc/phpmyadmin/private.pem';
$cfg['Servers'][$i]['ssl_ciphers'] = 'DHE-RSA-AES256-SHA';
```
