### ISSUE TITLE
recommended varnish configuration?

### ISSUE THREAD

**Issue by adixon** [phpmyadmin/docker#153]
Do you have a recommended varnish (vcl) configuration to work with this? When I'm running this behind my varnish, I get a blank screen - it's loading everything but giving me javascript console errors. I assume it's due to the one of the headers that varnish is mangling along the way (i.e. the x-forwarded-for, etc.), since it appears that nginx has some expectations in this regard.

I did use the PMA_ABSOLUTE_URI setting. Circumventing varnish works.

**Comment by williamdes** [comment]
I followed https://hub.docker.com/_/varnish and has no issue

**Comment by williamdes** [comment]
```yaml

  varnish:
    image: varnish
    container_name: varnish
    dns_search: williamdes.local
    hostname: varnish.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    mem_limit: 100m
    tmpfs:
      - /var/lib/varnish:exec
    volumes:
      - "/mnt/Dev/!OSS/servers/varnish/:/etc/varnish"
    networks:
      williamdeslocal:
        aliases:
          - varnish.williamdes.local
    ports:
      - "800:80"
      - "4430:443"
```
