### ISSUE TITLE
Can't make it work behind Nginx reverse proxy

### ISSUE THREAD

**Issue by r3c4ll** [phpmyadmin/docker#160]
I'm having an issue with phpmyadmin behind a nginx reverse proxy, my docker-compose.yml:
```yaml
version: '3'

services:
    reverse-proxy:
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        privileged: true
        restart: always

    joomla:
        image: joomla
        restart: always
        links:
            - joomla_db:mysql
        environment:
            VIRTUAL_HOST: joomla.reverse.com
            JOOMLA_DB_HOST: joomla_db
            JOOMLA_DB_PASSWORD: example

    joomla-pma:
        image: phpmyadmin/phpmyadmin
        links:
            - joomla_db:mysql
        restart: always
        environment:
            VIRTUALHOST: joomla-pma.reverse.com
            PMA_ABSOLUTE_URI: http://joomla-pma.reverse.com/
            PMA_HOST: joomla_db
            PMA_USER: root
            PMA_PASSWORD: example

    joomla_db:
        image: mysql:5.6
        restart: always
        environment:
        MYSQL_ROOT_PASSWORD: example
```

My /etc/hosts:
```
127.0.0.1 localhost
127.0.0.1 joomla.reverse.com
127.0.0.1 joomla-pma.reverse.com
```

So joomla.reverse.com is working fine, but joomla-pma.reverse.com return a 503 Service Temporarily Unavailable by nginx/1.13.12.

Any help is welcome!
