### ISSUE TITLE
PMADB introduction broke config auth without password

### ISSUE THREAD

**Issue by Soullivaneuh** [phpmyadmin/docker#164]
With the following `docker-compose.yml` extract:

```yaml
version: '2'

services:
  data:
    image: alpine
    volumes:
      - .:/code
      - ./docker/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro

  mysql:
    image: mysql:5.6
    volumes_from:
      - data
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - '8100:80'
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
```

The connection without password is not working anymore:

![image](https://user-images.githubusercontent.com/1698357/40178956-4479c17c-59e3-11e8-9f3b-5c54d407906c.png)

According to [this blame](https://github.com/phpmyadmin/docker/blame/5dd9a0f01561fd6def0883586c9609f80d3c9dad/etc/phpmyadmin/config.inc.php), the bug was introduced in https://github.com/phpmyadmin/docker/commit/93e2be73ecfb9b93f4473f3aa5a71052b4de5d11. While checking the env vars for PMADB, the `compress` and `AllowNoPassword` options was also moved to this condition.

Rollback to `4.8.0` image tag solve the issue for now.
