### ISSUE TITLE
disable auto login

### ISSUE THREAD

**Issue by mictadlo** [phpmyadmin/docker#180]
Hi,
I have the following phpmyadmin entries in my `docker-compose.yml` file:

```
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  links:
    - db
  ports:
    - 8183:80
  environment:
    PMA_USER: root
    PMA_PASSWORD: xxx
    #PMA_ARBITRARY: 1
```
When I open phpmyadmin is automatically log in. 

How is it possible to disable auto login?

Thank you in advance,

Michal
