### ISSUE TITLE
Can't mount volume with docker-compose

### ISSUE THREAD

**Issue by vladyslavstartsev** [phpmyadmin/docker#181]
I use `laradock`.
And I can't mount  - `./phpmyadmin/config/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php`
Looked [here](https://docs.phpmyadmin.net/en/latest/setup.html?highlight=docker-compose#customizing-configuration-file-using-docker-compose)
my `docker-compose.yml` phpmyadmin section looks like this
```yml
phpmyadmin:
  build: ./phpmyadmin
  volumes:
    - ./phpmyadmin/config/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
  environment:
    - PMA_ARBITRARY=1
    - MYSQL_USER=${PMA_USER}
    - MYSQL_PASSWORD=${PMA_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
  ports:
    - "${PMA_PORT}:80"
  depends_on:
    - "${PMA_DB_ENGINE}"
  networks:
    - frontend
    - backend
```
I do `docker-compose build --no-cache phpmyadmin` and then `docker-compose up -d phpmyadmin`. What it does is creates `phpmyadmin/config/config.user.inc.php` folder (!!!)

if I delete `phpmyadmin/config` folder, change `docker-compose.yml` phpmyadmin section to 
```yml
volumes:
  - ./phpmyadmin/config:/etc/phpmyadmin

```
do `docker-compose build --no-cache phpmyadmin` and then `docker-compose up -d phpmyadmin`, it will create `phpmyadmin/config` with files from container. BUT
1. My `phpmyadmin` login page changes 
from 
![image](https://user-images.githubusercontent.com/17382248/42897436-b487a234-8ac8-11e8-86d7-550c4fc5ea9d.png)

to 
![image](https://user-images.githubusercontent.com/17382248/42897479-d02fb95e-8ac8-11e8-923d-2d0d0db109ec.png)

Server input row is dropped

2. If I will try to change something there, for example I've tried to put `var_dump('random text');die;` in `phpmyadmin/config/config.user.inc.php` in will not be executed. At least if I visit `localhost:8080` (`laradock` default route for `phpmyadmin`) I will not see my `random text` in page source.
