### ISSUE TITLE
Cannot connect: invalid settings.

### ISSUE THREAD

**Issue by mictadlo** [phpmyadmin/docker#183]
Hi,
~I posted the same problem [here](https://serverfault.com/questions/924190/cannot-connect-invalid-settings-phpmyadmin).~

Currently, phpmyadmin is not able to connect to mariadb via docker-compose and I can't figure why.

`docker-compose.yml`:

```yaml
version: '3'
services:
  expressionbrowser:
      build: .
      restart: always
      ports:
          - "80:80"
      depends_on:
          - expressionbrowserdb
      volumes:
          - ./data/:/db

  expressionbrowserdb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=expressionbrowser
      - MYSQL_USER=browseradmin
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - expressionbrowserdb
    ports:
      - 8183:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: admin
      PMA_ARBITRARY: 1
```

`mysql/rna.sql`

```sql
CREATE DATABASE IF NOT EXISTS expressionbrowser;
CREATE USER 'browseradmin'@'localhost';
SET PASSWORD FOR 'browseradmin'@'localhost' = PASSWORD('password');
CREATE SCHEMA expressionbrowser;
GRANT ALL PRIVILEGES on expressionbrowser.* TO 'browseradmin'@'localhost';
```

`Dockerfile:`

```Dockerfile
FROM debian:stretch-backports
RUN apt-get update  && apt-get install -y --no-install-recommends \
    build-essential \
    apache2 \
    python-dev \
    python-setuptools \
    python-numpy \
    python-mysqldb \
    python-pip \
    python-wheel \
    git wget \
    ncbi-blast+ && \
    apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


#Based on: https://github.com/eriston/Apache-with-python-cgi-Docker
#load apache cgi module
RUN a2enmod cgi
RUN service apache2 restart

#enable cgi in the website root
#second block to allow .htaccess
RUN echo "                       \n \
<Directory /var/www/html>        \n \
   Options +ExecCGI              \n \
   AddHandler cgi-script .py     \n \
   DirectoryIndex index.py       \n \
</Directory>                     \n \
" >> /etc/apache2/apache2.conf

RUN chmod -R u+rwx,g+x,o+x /var/www/html

RUN pip install fisher goatools

RUN git clone https://github.com/nthomasCUBE/RNASeqExpressionBrowser.git
COPY ./example RNASeqExpressionBrowser/example

RUN cd RNASeqExpressionBrowser && \
    sed -i.bak "s|mysql_host::server|mysql_host::expressionbrowserdb|" installation_example.conf && \
    sed -i.bak "s|mysql_db::db|mysql_db::expressionbrowser|" installation_example.conf && \
    sed -i.bak "s|mysql_user::user|mysql_user::browseradmin|" installation_example.conf && \
    sed -i.bak 's|raw_input(">Please specify the absolute path to the directory where CSS file should be stored (within the /var/www/html directory, directory must exist) e.g. \[/var/www/html\]\\n") or my_input;|"/usr/lib/cgi-bin"|' installation.py && \
    sed -i.bak 's|raw_input(">Please specify the absolute path to the directory of the web server location, somewhere under e.g. \[/var/www/cgi-bin OR /usr/lib/cgi-bin\]\\n")|"/var/www/html"|' installation.py && \
    sed -i.bak 's|raw_input(">Please provide the path to the directory where R-output can be stored and accessed by apache-user e.g. \[/nfs/plantsp/webblast/data/\]\n")|"/data/webblast"|' installation.py #&& \
    #python installation.py installation_example.conf

EXPOSE 80
CMD /usr/sbin/apache2ctl -D FOREGROUND
```

What did I miss?

Thank you in advance.

Michal
