### ISSUE TITLE
Access denied for user 'root'@'ip'

### ISSUE THREAD

**Issue by mikeevstropov** [phpmyadmin/docker#195]
```yaml
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: xxx
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-migration:/docker-entrypoint-initdb.d

  myadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      VIRTUAL_HOST: xxx
      VIRTUAL_PORT: 80
      MYSQL_ROOT_PASSWORD: xxx
```
Access by phpmyadmin
```console
mysqli_real_connect(): (HY000/1045): Access denied for user 'root'@'ip' (using password: YES)
```
Access by localhost
```console
root@f35f1cc36c56:/# mysql -u root -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 12
Server version: 8.0.12 MySQL Community Server - GPL
```
