### ISSUE TITLE
phpmyadmin with https only

### ISSUE THREAD

**Issue by erwinvanlun** [phpmyadmin/docker#220]
I'm using the phpmyadmin/phpmyadmin package in a docker-compose file for a separate phpmyadmin container.

Goal: As a user, I'd like to access phpmyadmin like this:
https://www.mysite.com:8000
Sidenotes on the goal: Only with SSL to avoid password are being entered on http pages.. On localhost with a self signed certificate, on production with a certbot certificate (stored in a volume). 

As far as I understood, I have to modify the default nginx file. So my docker-compose file contains this section

```
        image: phpmyadmin/phpmyadmin
        links: 
            - mysql:db
        volumes:
            - ./config/phpmyadmin/nginx/mysite.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80

```
unfortunately, this 'mysite.conf' doesn't overwrite the default.conf file (that seems to be a Docker feature I can't avoid).

I also tried to create a separate dockerfile, using phpmyadmin/phpmyadmin as a basis, but my statements aren't reached because the phpmyadmin/phpmyadmin dockerfile ends with: 

```
ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD ["%%CMD%%"]
```
Sidenote: It is also difficult to enter the container with docker exec -t <container> /bin/bash, only separate commands can be issued. Also because of the entrypoint. 

Key question: how  to make sure I only have SSL traffic between browser and this container?
