### ISSUE TITLE
I cannot login to PMA -  Error #2002 - php_network_getaddresses: getaddrinfo failed

### ISSUE THREAD

**Issue by tommyJS** [phpmyadmin/docker#23]
I do not know what might be the case, but I cannot login to PMA. I have the following `docker-composer.yml` file:
```
db:
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=blabla
    - MYSQL_DATABASE=wordpress
  volumes_from:
    - datamysql

datamysql:
  image: debian:jessie
  volumes:
    - /mypath:/var/lib/mysql

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db:mysql
  ports:
    - "8080:80"
```
I tried to log in to PMA using `root` account and the given password: `blabla`.
I receive the following error:
```
#2002 - php_network_getaddresses: getaddrinfo failed: Name does not resolve — The server is not responding (or the local server's socket is not correctly configured).
```
Something wrong with my setup?

**Comment by nijel** [comment]
Maybe some issue with Docker DNS setup? Please check https://github.com/docker/docker/issues/14755

**Comment by AlainLaroche** [comment]
+1
I have the same mysql server name resolution problem since the mysql container is run with a volume to locate data on the host:
`docker run --name mysqlserver -v /host/dir:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:latest`
and PMA:
`docker run --name myadmin -d --link mysqlserver -p 8080:80 phpmyadmin/phpmyadmin`

Temporary solved by adding PMA_HOST environment variable:
`docker run --name myadmin -d --link mysqlserver -p 8080:80 -e PMA_HOST=mysqlserver phpmyadmin/phpmyadmin`

**Comment by nijel** [comment]
Has anything changed recently in Docker in this regard? In past nobody has complained about this and I'm pretty sure nothing has been changed on our side...

**Comment by AlainLaroche** [comment]
I'm new to Docker, I cannot say how it was even 2 weeks ago :)
Facts that I can report:
- PMA container with MySQL container without volume are working properly
- others containers like PHP or Webmin with MySQL container with volume are also OK
- PMA container with MySQL container with volume has name resolution problem

**Comment by RaphanW** [comment]
I encountered this error as well using docker-compose, wordpress, and phpmyadmin (see [this guide](https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-and-phpmyadmin-with-docker-compose-on-ubuntu-14-04)).

`#2002 - php_network_getaddresses: getaddrinfo failed: Name does not resolve — The server is not responding (or the local server's socket is not correctly configured).`

Issue solved using the suggestion of @AlainLaroche and adding the PMA_HOST environmental variable in `docker-composer.yml`.  See at the end of my file:

```
wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - 8080:80
wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: Pass123
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: Pass123
    PMA_HOST: mysql
```

I'm also completely new to Docker.

**Comment by JimyRyan** [comment]
It's the same for me on Docker Cloud. Below is an extract of my Stack config : 

pma:
  image: 'phpmyadmin/phpmyadmin:latest'
  environment:
    - PHP_UPLOAD_MAX_FILESIZE=100M
  links:
    - 'mariadb:db'
  ports:
    - '8080:80'

**Comment by personalaccount** [comment]
@JimyRyan is correct to use db instead of mysql. After adding the changes to a yml file, it is also a good idea to remove the existing container (not the image!), after stopping composer.
`~$ docker-compose stop`
`~$ docker-compose rm phpmyadmin`

docker-composer.yml should look similar to this:

```
maria_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: Securepass
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
        - maria_db:db
    ports:
        - 8181:80
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: Securepass
```

**Comment by gfelot** [comment]
Hi every one. I have the exact same problem even if it look like you commit a patch to solve this issue.

Here my docker-compose.yml v2 :

```
version: '2'
services:
  wordpress:
    image: wordpress:latest
    networks:
      - front
      - back
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DB_HOST: wordpress_db
    volumes:
      - ./wordpress-data:/var/www/html
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  wordpress_db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
    volumes:
      - wordpress-db-data:/var/lib/mysql
    networks:
      - back
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - back
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: azerty
      PMA_HOST: mysql
volumes:
    wordpress-db-data:
      driver: local
networks:
  front:
  back:
```

I have 3 issues on the login page of PMA :

` #2002 - php_network_getaddresses: getaddrinfo failed: Name does not resolve &mdash; The server is not responding (or the local server's socket is not correctly configured).`

`mysqli_real_connect(): php_network_getaddresses: getaddrinfo failed: Name does not resolve`

`mysqli_real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name does not resolve`

**Comment by Limbolindi** [comment]
so im giving up.
PLEASE HELP :cry: 

have read and tried a whole lot, and nothing will work:

Yeha i have tried 
PMA_HOST: db
(with links: - sqlDB:db)
 :-1: 

PMA_HOST: sqlDB
(with links: - sqlDB:sqlDB)
 :-1: 

PMA_HOST: mysql
(with links: - sqlDB:mysql)
 :-1: 
 
Even tried PMA_HOSTS and tried all kind of links :rofl: 

so PLEAS help me, i thought docker is cool, but im starting to HATE :rage:  it ;D 

```
version: '2'
services:
    sqlDB:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: mysecpasswd

    phpadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - sqlDB
        environment:
            PMA_HOSTS: slqDB, db, mysql
            MYSQL_ROOT_PASSWORD: mysecpasswd
        ports:
            - 127.0.0.1:32770:80
        links:
            - sqlDB:mysql
            - sqlDB:db
            - sqlDB:sqlDB
```
