### ISSUE TITLE
fpm-alpine does not work

### ISSUE THREAD

**Issue by lonix1** [phpmyadmin/docker#252]
The `fpm-alpine` image, which I assume refers to the latest version `4.9`, doesn't work:

Here is a very basic no frills `docker-compose.yml`:

````
version: '3.7'
services:

  mariadb:
    image: mariadb:10.4.8-bionic
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mariadb_data:/var/lib/mysql/
    networks:
      - pma

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:fpm-alpine
    environment:
      MYSQL_ROOT_PASSWORD: password
      PMA_HOST: mariadb
    ports:
      - '80:80'
    networks:
      - pma
    depends_on:
      - mariadb

volumes:
  mariadb_data:

networks:
  pma:
````

The app does not load.

If I use tag `latest` (rather than `fpm-alpine`) then it works.
