### ISSUE TITLE
can't connect to local mysql from the phpmyadmin container

### ISSUE THREAD

**Issue by khushbupatel24** [phpmyadmin/docker#271]
I have separate configuration of mysql database locally on the host machine. But I want to access it via docker service (web access).

Here is the "docker-compose.yml" file, in which I have configured phpmyadmin service to access local mysql db.

```yml
version: '3'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    env_file: "backend.env"
    networks:
      - app-network
    restart: always
```

**backend.env**

```
##########################################################################MYSQL
##########################################################################
MYSQL_USERNAME=root
MYSQL_ROOT_PASSWORD=dbpaswd

PMA_PORT=3306
PMA_HOST=<server ip address>
PMA_USER=root
PMA_PASSWORD=<root user password>
```

When I try to login, I got connection timeout error as below.

![image](https://user-images.githubusercontent.com/15361976/75247134-3f5fc100-57f7-11ea-8fd4-03b13495b419.png)

**Comment by williamdes** [comment]
Hi @khushbupatel24 
>  I have configured phpmyadmin service to access local mysql db.

Do you expect the phpmyadmin docker instance to access the database server on your machine ?
(and that the DB server is not a docker instance)

**Comment by williamdes** [comment]
https://docs.docker.com/compose/compose-file/#network-configuration-reference

You may be looking for `network: host`

**Comment by khushbupatel24** [comment]
@williamdes ,

yes, database is hosted locally on machine outside the docker.

**Comment by khushbupatel24** [comment]
> https://docs.docker.com/compose/compose-file/#network-configuration-reference
> 
> You may be looking for `network: host`

where should I specify this?

**Comment by williamdes** [comment]
> @williamdes ,
> 
> yes, database is hosted locally on machine outside the docker.

Okay, so what you are asking to docker is "impossible" without network mode set to host

> where should I specify this?

```yml
version: '3'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: "backend.env"
    networks: host
    restart: always
```

I hope you do not have any server running on the port 80 of your machine, if you have please stop it before
