### ISSUE TITLE
Container doesn't recognize when it's accessed via https over reverse proxy (traefik)

### ISSUE THREAD

**Issue by bd8392** [phpmyadmin/docker#276]
The Container throws a warning that it is not accessed via HTTPS...even if PMA_ABSOLUTE_URI is set with https, and traefik has ssl enabled...

**Comment by williamdes** [comment]
@bd8392 can you post your configuration ?

**Comment by bd8392** [comment]
yes =)

```  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    environment:
      PMA_ABSOLUTE_URI: https://phpmyadmin.someurl.yolo:5001/
    networks:
     - net
     - traefik_reverseproxy_net
    configs:
     -
      source: php.ini_for_phpmyadmin
      target: /usr/local/etc/php/php.ini
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.phpmyadminssl.tls: 'true'
        traefik.http.routers.phpmyadminssl.rule: Host(`phpmyadmin.someadress.yolo`)
        traefik.http.routers.phpmyadminssl.tls.certresolver: letsencrypt
        traefik.http.routers.phpmyadminssl.tls.options: secure-tls@file
        traefik.http.routers.phpmyadminssl.entrypoints: backend
        phpmyadmin.service.deployment.autoredeploy: 'true'
        traefik.http.services.phpmyadminlb.loadbalancer.passhostheader: 'true'
        traefik.docker.network: traefik_reverseproxy_net
        traefik.enable: 'true'
        traefik.http.services.phpmyadminlb.loadbalancer.server.scheme: http
        traefik.http.services.phpmyadminlb.loadBalancer.server.port: '80'```

**Comment by williamdes** [comment]
@bd8392 I tried 
```yml
version: "3"
services:
  traefik:
    image: "traefik:v2.1"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8092:8080"
      - "8093:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    environment:
      PMA_ABSOLUTE_URI: https://pma.traefik.local:5001/
    networks:
      - traefik_reverseproxy_net
    logging:
      driver: json-file
    labels:
      traefik.http.routers.phpmyadminssl.tls: "true"
      traefik.http.routers.phpmyadminssl.rule: Host(`pma.traefik.local`)
      traefik.http.routers.phpmyadminssl.tls.certresolver: letsencrypt
      #traefik.http.routers.phpmyadminssl.tls.options: secure-tls@file
      #traefik.http.routers.phpmyadminssl.entrypoints: backend
      phpmyadmin.service.deployment.autoredeploy: "true"
      traefik.http.services.phpmyadminlb.loadbalancer.passhostheader: "true"
      traefik.docker.network: traefik_reverseproxy_net
      traefik.enable: "true"
      traefik.http.services.phpmyadminlb.loadbalancer.server.scheme: http
      traefik.http.services.phpmyadminlb.loadBalancer.server.port: "80"

networks:
  traefik_reverseproxy_net:
    driver: bridge
```

Could you please help me to have a valid working example ?

**Comment by bd8392** [comment]
```
version: "3"
services:
  traefik:
    image: "traefik:v2.1"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.address=:443"
      - "--entryPoints.backend.address=:521"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--certificatesResolvers.letsencrypt.acme.email=your@email.com"
      - "--certificatesResolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesResolvers.letsencrypt.acme.tlsChallenge=true"
      - "--certificatesResolvers.letsencrypt.acme.keyType=RSA4096"
    ports:
      - "80:80"
      - "443:443"
      - "521:521"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/traefik/letsencrypt:/letsencrypt"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    environment:
      PMA_ABSOLUTE_URI: https://pma.traefik.local:521/
    logging:
      driver: json-file
    labels:
      traefik.http.routers.phpmyadminssl.tls: "true"
      traefik.http.routers.phpmyadminssl.rule: Host(`pma.traefik.local`)
      traefik.http.routers.phpmyadminssl.tls.certresolver: letsencrypt
      #traefik.http.routers.phpmyadminssl.tls.options: secure-tls@file
      #traefik.http.routers.phpmyadminssl.entrypoints: backend
      phpmyadmin.service.deployment.autoredeploy: "true"
      traefik.http.services.phpmyadminlb.loadbalancer.passhostheader: "true"
      traefik.docker.network: traefik_reverseproxy_net
      traefik.enable: "true"
      traefik.http.services.phpmyadminlb.loadbalancer.server.scheme: http
      traefik.http.services.phpmyadminlb.loadBalancer.server.port: "80"
```

This should do it...the traefik and phpmyadmin container have to be attached to the same network

**Comment by bd8392** [comment]
uncomment the entrypoint i forgot ist sorry

**Comment by williamdes** [comment]
Thank you the example file works fine
HTTP version says 404 but HTTPS one works fine https://pma.traefik.local:521/


```yml
version: "3"
services:
  traefik:
    image: "traefik:v2.1"
    networks:
      - traefik_reverseproxy_net
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.address=:443"
      - "--entryPoints.backend.address=:521"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--certificatesResolvers.letsencrypt.acme.email=your@email.com"
      - "--certificatesResolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesResolvers.letsencrypt.acme.tlsChallenge=true"
      - "--certificatesResolvers.letsencrypt.acme.keyType=RSA4096"
    ports:
      - "8082:80"
      - "4433:443"
      - "521:521"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/traefik/letsencrypt:/letsencrypt"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    networks:
      - traefik_reverseproxy_net
    environment:
      PMA_HOST: db-pma.traefik.local
      PMA_ABSOLUTE_URI: https://pma.traefik.local:521/
    logging:
      driver: json-file
    labels:
      traefik.http.routers.phpmyadminssl.tls: "true"
      traefik.http.routers.phpmyadminssl.rule: Host(`pma.traefik.local`)
      traefik.http.routers.phpmyadminssl.tls.certresolver: letsencrypt
      #traefik.http.routers.phpmyadminssl.tls.options: secure-tls@file
      #traefik.http.routers.phpmyadminssl.entrypoints: backend
      phpmyadmin.service.deployment.autoredeploy: "true"
      traefik.http.services.phpmyadminlb.loadbalancer.passhostheader: "true"
      traefik.docker.network: traefik_reverseproxy_net
      traefik.enable: "true"
      traefik.http.services.phpmyadminlb.loadbalancer.server.scheme: http
      traefik.http.services.phpmyadminlb.loadBalancer.server.port: "80"

  mysql5717:
    image: mysql:5.7.17
    container_name: db-pma.traefik.local
    dns_search: db-pma.traefik.local
    hostname: db-pma.traefik.local
    domainname: db-pma.traefik.local
    restart: on-failure:2
    networks:
      - traefik_reverseproxy_net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=public
      - MYSQL_USER=public
      - MYSQL_PASSWORD=public

networks:
  traefik_reverseproxy_net:
    driver: bridge
```


Unfortunately I could login

**Comment by bd8392** [comment]
yes you can login, but the admin interface shows that you don't acces ist via ssl

**Comment by williamdes** [comment]
SSL != HTTPS in the mysql world
I will post a link

**Comment by bd8392** [comment]
OHHHH THis means that you don't login to mariadb via ssl?

**Comment by williamdes** [comment]
Yes
https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_ssl

https://github.com/phpmyadmin/docker#environment-variables-summary

You could use `PMA_CONFIG_BASE64` for example to inject a custom config file

**Comment by bd8392** [comment]
Ok Thank you =) my bad...

**Comment by williamdes** [comment]
No worries, I was happy to try traefik for the first time

**Comment by bd8392** [comment]
Yes it's the best reverse proxy for docker I know :-) but it can become complicated when you insert headers and something like that...

**Comment by leo-at-itartpro** [comment]
If anyone stumbles upon this thread I managed to get it working with trial and error without having to create another entrypoint. I use my regular "websecure" entrypoint (port 443). Here is my docker-compose.yml solution for the phpmyadmin container:

```
  phpmyadmin:
    container_name: phpmyadmin
    logging:
        options:
          max-size: 5m
    env_file:
      - .env
    image: phpmyadmin
    restart: unless-stopped
    networks:
      - mytraefiknetwork
    tty: true
    depends_on:
      - mariadb
    environment:
      PMA_ABSOLUTE_URI: https://phpmyadmin.mywebsite.ru:40007
      APACHE_PORT: 40001
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=40007"
      - "traefik.http.services.phpmyadmin.loadbalancer.passhostheader=true"
      - "traefik.docker.network=mytraefiknetwork"

      - "traefik.http.middlewares.pma_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.pma_redirect.redirectscheme.permanent=true"

      - "traefik.http.routers.pma.service=phpmyadmin"
      - "traefik.http.routers.pma.rule=Host(`phpmyadmin.mywebsite.ru`)"
      - "traefik.http.routers.pma.tls=true"
      - "traefik.http.routers.pma.entrypoints=websecure"
      - "traefik.http.routers.pma.tls.certresolver=httpwebresolver"
      - "traefik.http.routers.pma.middlewares=pma_redirect"
```
