### ISSUE TITLE
UPOAD_LIMIT doesn't work in docker-compose

### ISSUE THREAD

**Issue by weider14** [phpmyadmin/docker#278]
Hello. I try to overwrite default memory limit by UPLOAD_LIMIT enviroment in docker-compose.yml file. But it doesn't work. 
Further my example of declaration pma in docker-compose.yml file.
```yml
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            - UPLOAD_LIMIT=100M
            - VIRTUAL_HOST=pma.local
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
        links:
            - mysql
        depends_on:
            - mysql
        restart: always
        volumes:
            - /Users/weider/tmp:/tmp
```
