### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR when trying to connect to https://mysite.com:8080

### ISSUE THREAD

**Issue by dnlml** [phpmyadmin/docker#279]
I have configured my container via docker-compose with the following settings:

```yml
phpmyadmin:
    depends_on:
      - mysite_mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysite_mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
```

When I try to access https://mysite.com:8080 I get "This site can’t provide a secure connection" followed by "ERR_SSL_PROTOCOL_ERROR".

It stoped working after I activate SSL on my domain using other docker containers.

What am I doing wrong?
AFAIK https implicitly uses the 443 port, so already setting 8080 sounds strange to me, but my knowledge here is very limited.

Thank you
