### ISSUE TITLE
Docker error "Could not reliably determine the server's fully qualified domain name."

### ISSUE THREAD

**Issue by AbDhops** [phpmyadmin/docker#293]
### Describe the bug
I am running mariadb and phpmyadmin in docker enviornment. Everything start smoothly. mariaDB server is running. However, phpmyadmin docker container complains about "AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.2. Set the 'ServerName' directive globally to suppress this message"

### To Reproduce
Use following docker compose to setup containers for mariaDB and phpmyadmin.
```yml
version: "3.7"

# to Enter in docker 
# docker exec -it some-mariadb bash
services:
  db:
    image: mariadb
    container_name: MariaDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      TZ: 'Europe/Berlin'
    ports:
      - 9306:3306
    volumes:
       - './database:/var/lib/mysql'

  myphpadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: MyPhpAdmin
    restart: always
    links:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: test
      TZ: 'Europe/Berlin'
    ports:
      - 8086:80
 
```
In container log we see error `AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.2. Set the 'ServerName' directive globally to suppress this message`

### Expected behavior

~~PhpMyAdmin shall able to start normally.~~
phpMyAdmin should not show this warning

### Server configuration
- mariadb : docker
- phpmyadmin: docker
