### ISSUE TITLE
Copy database to - Feature not working in phpMyAdmin when used with docker

### ISSUE THREAD

**Issue by aslamdoctor** [phpmyadmin/docker#307]
I am trying to duplicate a database using "Copy database to" feature in phpMyAdmin but it just keeps loading and don't duplicate the database. I am logged in as root user so it is supposed to work because normal users don't have rights to create new database but root has.
Below is my yml file code

```yml
phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    restart: always
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 256mb
    container_name: wp_phpmyadmin
    networks:
      - wp_network
```
