### ISSUE TITLE
Blank white page when using proxy and Nginx

### ISSUE THREAD

**Issue by jaywork2020** [phpmyadmin/docker#310]
This repository contains only Docker integration of phpMyAdmin.

Please do not report bugs in phpMyAdmin itself here, use
<https://github.com/phpmyadmin/phpmyadmin/issues> instead.

I am running this `phpmyadmin` image on ubuntu and it is running on port 8010. I can see the login form when browsing `echo $(wget localhost:8010 -q -O -)`

I am trying to expose the app to the outside work using `adminusa.mydomain.com` I am using Nginx to allow me to host multiple sites on the same server. But when I access the site using adminusa.mydomain.com I get blanc white page. I am not sure what I am doing wrong here.

Here is the Ngix config for `adminusa.mydomain.com` I am guessing that the `root` path is wrong. I currently commented out that line but now sure what should the root be in this case.

```
server {
    listen 80;
    server_name adminusa.myadmin.com;

    return 301 https://adminusa.myadmin.com$request_uri;
}

server {
    listen 443 ssl;
    server_name adminusa.myadmin.com;

    #root /var/www/html;   <<<<<< WHAT SHOULD THE ROOT VALUE BE SET TO???

    ssl_certificate       /etc/ssl/certs/adminusa.myadmin.com.crt;
    ssl_certificate_key   /etc/ssl/certs/adminusa.myadmin.com.key;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    access_log off;

    error_log /var/log/nginx/adminusa.myadmin.com-error.log;

    index index.html index.php;
    # server_token off;

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires max;
        log_not_found off;
    }

    location / {
        proxy_pass http://localhost:8010;
        proxy_set_header HOST $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

Here is my part in my docker-compose.yml file that runs the phpmyadmin image

```
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
            PMP_HOST: mysql_server:3306
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: mysql_root_pasword
        depends_on:
            - mysql_server
        ports:
            - 8010:80
```

How can I correctly expose this image to the outside world using nginx?
