### ISSUE TITLE
AH00534: apache2: Configuration error: No MPM loaded.

### ISSUE THREAD

**Issue by derekoharrow** [phpmyadmin/docker#311]
I've just moved my docker config to a new host VM (had to reinstall to upgrade from Ubuntu 18.04 to 20.04.1 LTS)
Everything is working fine, except for phpmyadmin
When I try to run the container, I get the following in the log file and the container just keeps restarting:
```
AH00534: apache2: Configuration error: No MPM loaded.
AH00534: apache2: Configuration error: No MPM loaded.
AH00534: apache2: Configuration error: No MPM loaded.
```

The mariadb database is running fine.

Here's my docker compose:
```yml
  phpmyadmin:
    hostname: phpmyadmin
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    ports:
      - 9102:80
    networks:
      - web
      - default
    volumes:
      - /etc/hosts:/etc/hosts:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=${TZ}
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=mypasswordhere
    restart: unless-stopped
```
Any idea why?
