### ISSUE TITLE
How to get Upload Dir ($cfg['UploadDir']) working using volume to import SQL files ?

### ISSUE THREAD

**Issue by CedricGoby** [phpmyadmin/docker#312]
Hi,

I'm testing phpmyadmin/docker and I'm trying to use this phpmyadmin feature : https://docs.phpmyadmin.net/en/latest/config.html#cfg_UploadDir
> The name of the directory where SQL files have been uploaded by other means than phpMyAdmin (for example, ftp).
> Those files are available under a drop-down box when you click the database or table name, then the Import tab.

I tried this using docker-compose :
- Create a directory into the container : /var/www/html/ftp
- Create a volume host:container : /home/bob/pma/ftp:/var/www/html/ftp
- Copy a sql file into the host (/home/bob/pma/ftp)

But if I open phpmyadmin and go to the import tab I can't see no drop-down box...

![drop-down-import-phpmyadmin-docker](https://user-images.githubusercontent.com/17612749/98162439-a6368d80-1ee1-11eb-8156-6bf8c9b811dd.png)

Before launching docker-compose and create the container we can have a look into the host file system :
```
ls -l /home/bob/pma
drwxr-xr-x 2 bob bob 4096 Nov  4 18:14 config
```

There is only one directory (config), this is where the custom phpmyadmin config is stored.

Then I launch docker-compose and after a few seconds the container is up and running.

Let's have a look into the host again :
```
ls -l /home/bob/pma/
drwxr-xr-x 2 bob bob 4096 Nov  4 18:14 config
drwxr-xr-x 2 root    root    4096 Nov  4 18:07 ftp
```
As you can see, the container has created the "ftp" directory as expected.

Then I copy a sql file (short.sql) into the host into "/home/bob/pma/ftp"
We can see the file from the host :
```
ls /home/bob/pma/ftp/
short.sql
```

Now let's go into the container : 
```
docker exec -it bob-pma /bin/bash
```

The sql file is in the container too
```
root@be964bd91b57: ls -l ftp
-rw-r--r-- 1 root root 899 Nov  4 18:07 short.sql
```
So this sql file should be available from import tab in phpmyadmin, but it's not the case.

Could you please help me ?

Here is my docker-compose file :
```yml
version: '3.1'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    build: .
    container_name: bob-pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: https://domain.tld/
      UPLOAD_LIMIT: 3000000000
    volumes: 
      - /home/bob/pma/config/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - /home/bob/pma/ftp:/var/www/html/ftp
    restart: always
    ports:
      - 8081:80
```

The Dockerfile :
```
RUN mkdir /var/www/html/ftp
```
 
The custom phpmyadmin custom file :
```php
cat /home/bob/pma/config/config.user.inc.php 
$cfg['ExecTimeLimit'] = 0;
$cfg['UploadDir'] = '/var/www/html/ftp';
```
Regards
