### ISSUE TITLE
Not working on Pi 4 with hypriot-os

### ISSUE THREAD

**Issue by bd8392** [phpmyadmin/docker#316]
This repository contains only Docker integration of phpMyAdmin.

Please do not report bugs in phpMyAdmin itself here, use
<https://github.com/phpmyadmin/phpmyadmin/issues> instead.

The Image is not working on the pi 4 with hypriot os...get the following logs:
```
standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by williamdes** [comment]
Hi,
Could you paste here your docker-compose or docker configuration?

**Comment by bd8392** [comment]
Yes :-)

```
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
    labels:
      - "traefik.enable=true"
      # Backend-Section
      - "traefik.http.routers.phpmyadminbackend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.phpmyadminbackend.entrypoints=phpmyadmin"
      - "traefik.http.routers.phpmyadminbackend.tls=true"
```
also tested with another image (jackgruber/phpmyadmin) which works... You can ignore the traefik-Section and open up direct port instead
