### ISSUE TITLE
fpm-alpine + haproxy

### ISSUE THREAD

**Issue by qeepcologne** [phpmyadmin/docker#327]
i'm trying to switch from pma to pma-fpm-alpine

haproxy.cfg
(following https://www.haproxy.com/de/blog/load-balancing-php-fpm-with-haproxy-and-fastcgi/)

```
backend pma
  mode http
  server pma 10.10.10.200:80 maxconn 20 verify none check`
```
=>
```
backend pmafpm
  use-fcgi-app php-fpm
  server pma 10.10.10.209:9000 proto fcgi

fcgi-app php-fpm
  log-stderr global
  docroot /var/www/html
  index index.php
  path-info ^(/.+\.php)(/.*)?$
```

docker-compose.yml
```yml
version: '3.8'
services:
  phpmyadmin:
    container_name: pmafpm
    image: phpmyadmin/phpmyadmin:5.1.0-fpm-alpine
    environment:
      - PMA_HOST=users_db
      - PMA_ABSOLUTE_URI=https://pma-staging.qeep.net
      - PMA_USER=removed
      - PMA_PASSWORD=removed
    networks:
      mynet:
        ipv4_address: 10.10.10.209
    volumes:
     - /sessions
     - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    restart: unless-stopped
networks:
     mynet:
        external:
          name: haproxy_mynet
```

first problem:
had to edit /usr/local/etc/php-fpm.d/www.conf and add .js .css .png .gif .ico .map to security.limit_extensions 

second problem:
unusable slow
could be improved by increasing pm.max_children  and pm.max_spare_servers 

the result is starting up, but css still looks missing/broken, it's still very slow and there is some error output
```
Notice in ./libraries/classes/Controllers/HomeController.php#177
 Undefined index: SERVER_SOFTWARE

Backtrace

./libraries/classes/Routing.php#186: PhpMyAdmin\Controllers\HomeController->index(array)
./index.php#18: PhpMyAdmin\Routing::callControllerForRoute(
string '/',
,
```

Is anybody using current fpm-alpine?
