### ISSUE TITLE
docker compose parameter UPLOAD_LIMIT not working in v5.1.0

### ISSUE THREAD

**Issue by vc05946** [phpmyadmin/docker#328]
The docker compose parameter UPLOAD_LIMIT not working in v5.1.0, I have tried to fallback to phpmyadmin:5.0.2 and it works.

**Comment by ibennetch** [comment]
I've tried this with both vanilla Docker and docker-compose, and both seem to work correctly for me. Can you tell us a little more about what isn't working for you, and the commands you are using?

With docker-compose, I just added another line to the provided [docker-compose.yml](https://github.com/phpmyadmin/docker/blob/master/docker-compose.yml) for the UPLOAD_LIMIT. I'll provide my docker commands below.

```

docker run -e UPLOAD_LIMIT=9999 -p 9999:80 -t -d phpmyadmin:latest

root@50ecfb85abdc:/usr/local/etc/php/conf.d# cat /usr/local/etc/php/conf.d/phpmyadmin-upload-limit.ini

upload_max_filesize = 9999
post_max_size = 9999
```

I create a new file `/var/www/html/info.php`:

```
<?php

phpinfo();
```

Then I loaded that in my browser: http://localhost:9999 and in the "Environment" section, I see the value is properly applied: UPLOAD_LIMIT | 9999

**Comment by williamdes** [comment]
What value did you set @vc05946 ?

**Comment by vc05946** [comment]
> What value did you set @vc05946 ?

I have used opencart for the application. For the docker-compose.yml, it is set like:

```
version: "3.2"
services:
 mysql:
    image: mysql:8.0
    container_name: yyy-mysql
    hostname: yyy-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=xxx
      - MYSQL_ROOT_PASSWORD=xxx
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
 opencart:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: yyy-opencart
    hostname: yyy-opencart
    restart: always
    environment:
      - ENVIRONMENT=Development
    ports:
      - "10001:80"
    volumes:
      - .:/var/www/html:Z
    depends_on:
      - mysql
 phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: yyy-phpmyadmin
    hostname: yyy-phpmyadmin
    restart: always
    ports:
      - "10004:80"
    environment:
      PMA_HOST: "mysql"
      UPLOAD_LIMIT: 102400K
    links:
      - "mysql: mysql"
```

**Comment by ibennetch** [comment]
Using your docker-compose.yml, it appears as if the value is correctly applied:

<img width="788" alt="image" src="https://user-images.githubusercontent.com/1443710/111260173-bc262e80-85f6-11eb-826c-ba2c674d2939.png">


Can you tell us more about what problem you're seeing and what isn't working for you?

**Comment by vc05946** [comment]
> Using your docker-compose.yml, it appears as if the value is correctly applied:
> 
> <img alt="image" width="788" src="https://user-images.githubusercontent.com/1443710/111260173-bc262e80-85f6-11eb-826c-ba2c674d2939.png">
> 
> Can you tell us more about what problem you're seeing and what isn't working for you?

No problem.

The main problem at that time is that the import maximum size in phpmyAdmin didn't change, it kept to be 2048KB even I have updated the UPLOAD_LIMIT. (Below can be updated to 100MiB successfully if I set the version of phpmyadmin image to 5.0.2)

![image](https://user-images.githubusercontent.com/4089503/111261575-a435c580-865d-11eb-9b22-00c9dd9bb5d8.png)

**Comment by ibennetch** [comment]
Thanks, we will keep looking in to this.

**Comment by ibennetch** [comment]
I'm baffled why this isn't working for you, the limit is showing as 100 MiB for me.

<img width="576" alt="image" src="https://user-images.githubusercontent.com/1443710/111387596-584a4700-8684-11eb-952a-363766505885.png">

**Comment by ibennetch** [comment]
I'm baffled by this, using your docker-compose.yml I get the expected 100MiB max shown in phpMyAdmin (using phpMyAdmin/phpmyadmin:latest). I can't reproduce the problem you're seeing.

The next thing I'd look at is the architecture you're running this on, is it 64 bit, any special characteristics like ARM or Sparc, etc?

**Comment by vc05946** [comment]
> I'm baffled by this, using your docker-compose.yml I get the expected 100MiB max shown in phpMyAdmin (using phpMyAdmin/phpmyadmin:latest). I can't reproduce the problem you're seeing.
> 
> The next thing I'd look at is the architecture you're running this on, is it 64 bit, any special characteristics like ARM or Sparc, etc?

I think there does not have some special characteristics, let me provide part of system info for you to reference:
![image](https://user-images.githubusercontent.com/4089503/111726853-adfd3a00-88a4-11eb-9101-9c09bd6d78ec.png)

and:

PHP_VERSION: 7.4.11

**Comment by williamdes** [comment]
Hi @vc05946 

I did narrow down your file to
```yml
version: "3.2"
services:
 mysql:
    image: mysql:8.0
    container_name: yyy-mysql
    hostname: yyy-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=xxx
      - MYSQL_ROOT_PASSWORD=xxx
    restart: always
 phpmyadmin:
    image: phpmyadmin:latest
    container_name: yyy-phpmyadmin
    hostname: yyy-phpmyadmin
    restart: always
    ports:
      - "10004:80"
    environment:
      PMA_HOST: "yyy-mysql"
      UPLOAD_LIMIT: 102400K
    links:
      - "mysql: mysql"

```

With changing the PMA_HOST value and  `image:` to use the Docker official image
I can confirm the value of 100Mib after login with root/xxx
