### ISSUE TITLE
phpmyadmin/phpmyadmin:5.1.1-fpm docker image is not configured properly

### ISSUE THREAD

**Issue by mmm4m5m** [phpmyadmin/docker#333]
### Describe the bug

Connection is closed when trying to load the page.

### To Reproduce

Follow the installation steps:
https://docs.phpmyadmin.net/en/latest/setup.html#using-docker-compose

### Server configuration

docker image: phpmyadmin/phpmyadmin:5.1.1-fpm

### Additional context

The apache image works fine: phpmyadmin/phpmyadmin:5.1.1
Fpm image listen on port 9000. Probably on ipv6 (or 127.0.0.1?).
Quick changes in docker-compose and php-frm config files did not help.

**Comment by mmm4m5m** [comment]
hi @williamdes 

Sorry for the late answer. I checked different options with **FPM** image without success.
Currently I am using this docker-compose with **not-FPM** image.
It works as expected with different options (for example with network host).

```
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: phpmyadmin-5.1.1
    volumes:
      - /sessions
      - ${PWD}/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./phpmyadmin/theme/:/www/themes/theme/
    environment:
      PMA_ARBITRARY: 1
    ports:
      - 127.0.0.1:8888:80
    #network_mode: host
```
