### ISSUE TITLE
Subdirectory Nginx Proxy_pass

### ISSUE THREAD

**Issue by jonathanmmm** [phpmyadmin/docker#334]
Hi,

I found this one https://github.com/phpmyadmin/docker/issues/101 but this is not about nginx.
and tried many different ways, but I can't get it right

```nginx
server {
listen 8080;
server_name 192.168.10.1;
  location /mysql {
    rewrite /mysql/([^/]+) /$1 break;
    set $upstream_phpmyadmin phpmyadmin:80;
    proxy_pass http://upstream_phpmyadmin/;
    proxy_pass_header Content-Type;
  }
}
```
The PMA_URI is in docker-compose.yml
`- PMA_ABSOLUTE_URI=http://192.168.10.1/mysql/`

nginx is inside a container and has -p 80:8080 to the outside world

I get the following error in browser (chromium) console:
crbug/1173575, non-JS module files deprecated.

sometimes I got 404 forbidden or not found, e.g. with css/js, tried a lot and couldn't get it to work.

Does somebody know how to solve this?
I try the same setup with an phplapadmin container and it didn't work either.

without subfolder it works.

**Comment by williamdes** [comment]
What version are you using?

**Comment by jonathanmmm** [comment]
I am using:
phpmyadmin 5.1.1 (from webinterface)

in docker-compose I use:
image: phpmyadmin as image

**Comment by williamdes** [comment]
Thank you !

I think you meant "in the docker-compose network" for "nginx is inside a container and has -p 80:8080 to the outside world"

### Config to reproduce the error

```yml
version: "3"

services:
  phpmyadmin-frontend:
    image: phpmyadmin:latest
    environment:
        PMA_ABSOLUTE_URI: http://localhost:8075/mysql/
  nginx:
    image: nginx:alpine
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/nginx.conf"
    ports:
      - "8075:8080"
```

```nginx
server {
 listen 8080;
 server_name localhost;
   location /mysql {
     rewrite /mysql/([^/]+) /$1 break;
     set $upstream_phpmyadmin phpmyadmin-frontend:80;
     proxy_pass http://upstream_phpmyadmin/;
     proxy_pass_header Content-Type;
   }
}
```

### Config to fix the error

I think `http://upstream_phpmyadmin/;` was meant to be `http://$upstream_phpmyadmin/;` and the `rewrite` regex was not working

Source: https://stackoverflow.com/a/47447211/5155484

```
.
├── docker-compose.yml
└── nginx.conf

0 directories, 2 files
```

```yml
version: "3"

services:
  phpmyadmin-frontend:
    image: phpmyadmin:latest
    container_name: phpmyadmin-frontend
    environment:
        PMA_ABSOLUTE_URI: http://localhost:8075/mysql/

  nginx:
    image: nginx:alpine
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro"
    ports:
      - "8075:8080"
```

```nginx
server {
 listen 8080;
 server_name localhost;
 set $upstream_phpmyadmin phpmyadmin-frontend:80;
   location /mysql {
     resolver 127.0.0.11; # Docker internal DNS
     rewrite ^/mysql(/.*)$ $1 break;
     proxy_pass http://$upstream_phpmyadmin;
     proxy_set_header X-Real-IP  $remote_addr;
     proxy_set_header X-Forwarded-For $remote_addr;
     proxy_set_header Host $host;
   }
}
```

Url to access: `http://localhost:8075/mysql/` (last `/` is very important)
