### ISSUE TITLE
Issue with arm64

### ISSUE THREAD

**Issue by Nv7-GitHub** [phpmyadmin/docker#336]
I am trying to run this on my Raspberry Pi Model 4 B (64-bit OS). When I run it, I get the error
```
standard_init_linux.go:228: exec user process caused: exec format error
```
I read that this was an error related to arm64. Is it possible to run phpMyAdmin with arm64 on a Raspberry Pi Model 4 B?

**Comment by Nv7-GitHub** [comment]
I tried using https://hub.docker.com/r/ebspace/armhf-phpmyadmin, which worked but just gave the apache2 default page instead of phpMyAdmin.

**Comment by williamdes** [comment]
You need to use the official Docker image :)
`phpmyadmin:latest`

**Comment by Nv7-GitHub** [comment]
I originally used the official one, that is the one that got the exec error.

**Comment by williamdes** [comment]
> I originally used the official one, that is the one that got the exec error.

Could you please paste your docker-compose file ?

**Comment by Nv7-GitHub** [comment]
You can view the file I used at https://github.com/Nv7-GitHub/Nv7Haven/blob/76f2115b7197eaa4cf1d8e40c0b4356ace9df45d/docker-compose.yml#L18

**Comment by Nv7-GitHub** [comment]
Basically, I originally used the official docker image but got the exec error. Then I tried using that arm docker image, but that gave the apache2 default page.

**Comment by williamdes** [comment]
Can you try 
```yml
  phpmyadmin:
    image: phpmyadmin:latest
    depends_on: 
      - db
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 1G
    ports:
      - "${PHP_PORT}:80"
    restart: unless-stopped
```

I did not see that you tried the official image in your commits :)
See: https://hub.docker.com/_/phpmyadmin (`image: phpmyadmin`)

As you can see on the web page they built the image for arm64
