### ISSUE TITLE
Change of Default Port 80

### ISSUE THREAD

**Issue by AbDhops** [phpmyadmin/docker#340]
I have working setup of MariaDB and PHP My admin on synology docker. In this, I would like to change default port 80 to something else. Can some one guide me how to do it ?

PS : I know I can map the port like below.  But making this, runs the container into dedicated network. Which restrics the access from the host machine. 
```yaml
    ports:
      - "8090:80"
```

By changing the default port, I want to change the network mode to "host". So all other applications from the host machine can also access this docker container services.

**Comment by williamdes** [comment]
Hi @AbDhops 

I perfectly understand the issue you are having, would https://github.com/phpmyadmin/docker/issues/271#issuecomment-898046648 be a workaround ?

**Comment by williamdes** [comment]
Here is a tutorial for socket access: https://github.com/phpmyadmin/docker/issues/271#issuecomment-898884172

Let me know if it helps

**Comment by Largo** [comment]
OP and me would like the server inside the container to use a different port. The bitnami image can do this, but it does not run on arm64. It would be nice to have the same sort of environment variable in the offical image.

`     - APACHE_HTTP_PORT_NUMBER=8090`

```
phpmyadmin:
    image: docker.io/bitnami/phpmyadmin:5
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT_NUMBER=3306
      - APACHE_HTTP_PORT_NUMBER=8090
      - PHPMYADMIN_ALLOW_REMOTE_CONNECTIONS=true
      - DATABASE_ENABLE_SSL=false
```

**Comment by devinmatte** [comment]
Any updates to this? Had to switch to `bitnami/phpmyadmin` until this image supports changing the running port to something other than 80 as it it's required to run as non-root #187

**Comment by williamdes** [comment]
> Any updates to this? Had to switch to `bitnami/phpmyadmin` until this image supports changing the running port to something other than 80 as it it's required to run as non-root #187

This will be available on the next phpMyAdmin version, thank you for contributing !

**Comment by williamdes** [comment]
This is now live on https://hub.docker.com/_/phpmyadmin

**Comment by ttodua** [comment]
> This is now live on [hub.docker.com/_/phpmyadmin](https://hub.docker.com/_/phpmyadmin)
```
  pma_my:
    image: phpmyadmin:latest
    environment:
      APACHE_PORT: 8123
```
