### ISSUE TITLE
PMA_PMADB not work in docker 

### ISSUE THREAD

**Issue by EngAly** [phpmyadmin/docker#344]
I try to show the bookmark feature in PHPMyAdmin but not appear. 

docker-compose.yml
```yml
version: '2.3'
services:

 mysql:
   image: mysql
   container_name: mysql
   restart: always
   ports:
     - "3306:3306"
   volumes:
     - ./mysql:/var/lib/mysql
   environment:
      MYSQL_DATABASE: test
      # MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
 phpmyadmin:
   image: phpmyadmin/phpmyadmin:5.1.1
   restart: always
   container_name: phpmyadmin
   depends_on:
     - mysql
   ports:
     - "80:80"
   environment:
     PMA_HOST: mysql
     PMA_PMADB: phpmyadmin
     MYSQL_ROOT_PASSWORD: root
     UPLOAD_LIMIT: 1G
     # MAX_LIFE_TIME: 100000
     MAX_EXECUTION_TIME: 100000
```
