### ISSUE TITLE
raspberry pi nothing shows in browser

### ISSUE THREAD

**Issue by khandakershahi** [phpmyadmin/docker#356]
Hi
I was trying to setup wordpress, mysql and phpmyadmin in raspberry pi 4 with portainer. In the browser it shows nothing expect the favicon.

Here is my yml code:

```
version: '2.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8585:80
    environment:
      PUID: 1000
      PGID: 100
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      LIVE_URL: http://lepetitcoquelicotfleurs1.local
    volumes:
      - /srv/dev-disk-by-uuid-f88f3aae-ef9e-467e-8bc4-02ecd4bdc1c8/Pidata/app1/wordpess:/var/www/html

    links:
      - db:db
    networks:
      - app-network

  db:
    image: ghcr.io/linuxserver/mariadb
    environment:
      - PUID=1000
      - PGID=100
      - MYSQL_ROOT_PASSWORD=changeme
      - TZ=Aisa/Dhaka
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=password #Must match the above password
    volumes:
      - /srv/dev-disk-by-uuid-f88f3aae-ef9e-467e-8bc4-02ecd4bdc1c8/Pidata/app1/db1:/config
    ports:
      - 3333:3306
    restart: unless-stopped
    networks:
      - app-network
  
 # phpmyadmin
  phpmyadmin:
    image: arm32v7/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_VERBOSE: wordpress
      PMA_PORT: 3306
      PMA_USER: wordpress
      PMA_PASSWORD: changeme
    volumes:
      - /srv/dev-disk-by-uuid-f88f3aae-ef9e-467e-8bc4-02ecd4bdc1c8/Pidata/app1/adminer:/config
    links:
      - db:db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge 
```
and here is the log of phpmyadmin container:

```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.0.2. Set the 'ServerName' directive globally to suppress this message

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.0.2. Set the 'ServerName' directive globally to suppress this message

[Fri Mar 11 09:01:18.004071 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/8.0.16 configured -- resuming normal operations

[Fri Mar 11 09:01:18.004219 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

192.168.100.36 - - [11/Mar/2022:09:01:25 +0000] "GET / HTTP/1.1" 200 229 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"

192.168.100.36 - - [11/Mar/2022:09:01:26 +0000] "GET / HTTP/1.1" 200 228 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"

192.168.100.36 - - [11/Mar/2022:09:01:27 +0000] "GET / HTTP/1.1" 200 228 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"

192.168.100.36 - - [11/Mar/2022:09:01:28 +0000] "GET / HTTP/1.1" 200 228 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"

192.168.100.36 - - [11/Mar/2022:09:01:33 +0000] "GET /phpmyadmin HTTP/1.1" 404 511 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"

192.168.100.36 - - [11/Mar/2022:09:01:39 +0000] "GET / HTTP/1.1" 200 229 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"

192.168.100.36 - - [11/Mar/2022:09:01:40 +0000] "GET / HTTP/1.1" 200 228 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"

192.168.100.36 - - [11/Mar/2022:09:01:40 +0000] "GET / HTTP/1.1" 200 228 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"

192.168.100.36 - - [11/Mar/2022:09:01:41 +0000] "GET / HTTP/1.1" 200 228 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
```
I don't what is wrong here.
Thanks
Shahi
