### ISSUE TITLE
Export SQL Fail  network error

### ISSUE THREAD

**Issue by ChronosRoot** [phpmyadmin/docker#357]
![image](https://user-images.githubusercontent.com/53171939/160295579-0b3aba65-d681-48c6-9e29-f5955a9291cf.png)
Environment: k3s
Version: 5.1.3
When I export sql, I get a network error, deploy it on k3s, use nginx reverse proxy, everything works fine in version 5.1.1

**Comment by UnwishingMoon** [comment]
Same problem, I have phpmyadmin deployed on docker behind a nginx proxy. I tried some debugging and at the end I reverted to 5.1.1

I enabled nginx debug in error.log and here is the line:
```
*96 client canceled stream 1 while reading upstream, client: ...
```
I tried first editing nginx `proxy_buffering` alongside `proxy_request_buffering` without luck
I changed phpmyadmin `mime_type` variable inside `Export.php` class just to be sure but without success

I fired up a test env with just phpmyadmin and a test database connecting with localhost (excluding nginx entirely) and the problem persist

**Comment by williamdes** [comment]
Hi

Could you share some config files so I can try to reproduce this on my end ?

Does 5.1.2 work ?
So 5.1.3 does not work, right ?

**Comment by UnwishingMoon** [comment]
I did not tried with 5.1.2 because from `https://hub.docker.com/_/phpmyadmin` there is no 5.1.2 tag

Here is my docker-compose.yml file I used as a test to exclude nginx:
```
services:
  db:
    image: mariadb:10
    environment:
      - MARIADB_ROOT_PASSWORD=root

  pma:
    image: phpmyadmin:5.1.3-apache
    ports:
      - 127.0.0.1:9000:80
    environment:
      - HIDE_PHP_VERSION=true
      - UPLOAD_LIMIT=30M
```

I tried port `9000` and port `80` and the error shows up but if port `8080` is used the file is not downloaded at all
While using the image with port `8080` the network tab in chrome shows `(failed)net::ERR_CONTENT_DECODING_FAILED`

The response headers:
```
HTTP/1.1 200 OK
Date: Mon, 28 Mar 2022 14:28:48 GMT
Server: Apache/2.4.52 (Debian)
Expires: Mon, 28 Mar 2022 14:28:48 +0000
Cache-Control: no-store, no-cache, must-revalidate,  pre-check=0, post-check=0, max-age=0
Last-Modified: Mon, 28 Mar 2022 14:28:48 +0000
X-ob_mode: 1
Content-Encoding: gzip
Vary: Accept-Encoding
Pragma: no-cache
Content-Description: File Transfer
Content-Disposition: attachment; filename="files.sql"
Content-Transfer-Encoding: binary
Keep-Alive: timeout=5, max=43
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: text/x-sql;charset=utf-8
```
