### ISSUE TITLE
phpMyAdmin can't connect to mysql - both on same network.

### ISSUE THREAD

**Issue by tcconway** [phpmyadmin/docker#360]
Somewhat new to Docker, so it might be a user error...

After having following several YT tutorials, I cannot get PHPMyAdmin to actually log in--I get the following errors:
- mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known
- mysqli::real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known

My setup is:
Docker with the default Laravel setup. Both 'mysql' and 'phpmyadmin' are in the 'sail' network.

Here's my docker-compose.yml:
```yml
# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin
        environment:
            - PMA_HOST = mysql
            - PMA_PORT = 3306
        networks:
            - sail
        ports:
            - 8080:80
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
```

**Comment by tcconway** [comment]
Apparently setting - PMA_ARBITRARY=1 in the yml and then using 'mysql' during login works...

**Comment by williamdes** [comment]
> Apparently setting - PMA_ARBITRARY=1 in the yml and then using 'mysql' during login works...

What about using
```yml
       environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
```
it should work fine
