### ISSUE TITLE
mysqli::real_connect(): (HY000/2002): No such file or directory

### ISSUE THREAD

**Issue by falahdoclo12** [phpmyadmin/docker#365]
Im install phpmyadmin with docker but can't login to my phpmyadmin

im using ubuntu Ubuntu 20.04 LTS x64

```yml
version: '3.4'
services:
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password123!"
    restart: always
    volumes:
    - '/data/mysql:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mariadb:db
    ports:
      - 9500:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: "password123!"
      UPLOAD_LIMIT: 300M

  redis:
    image: 'bitnami/redis:latest'
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD="password123!"
    volumes:
      - '/data/redis-data:/bitnami'
```
