### ISSUE TITLE
Themes broken in 5.2.0 container?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [phpmyadmin/docker#367]
### To Reproduce

Don't know. All I did was update the container to the latest and now themes wont load. I may be wrong, but it seems like the path is wrong? (see screenshot).

### Expected behavior

Themes load.

### Screenshots

![image](https://user-images.githubusercontent.com/39491297/170769404-b7a78a6b-946e-4fdf-8d44-0b9690e38f50.png)

### Server configuration

- Operating system: Ubuntu latest in docker desktop wsl2

**Comment by YouveGotMeowxy** [comment]
> Hi @YouveGotMeowxy This is quite strange, can you share your docker-compose file ?

Happy to. :)

```
  phpmyadmin:
    hostname: 'phpmyadmin'
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      TZ: 'America/Chicago'
      PMA_HOST: 'mysql'
      MYSQL_ROOT_PASSWORD_FILE: '/run/secrets/MySQL-PW'
      PMA_ABSOLUTE_URI: 'https://phpmyadmin.redacted.com/'
    volumes:
      - '/opt/docker/configs/phpmyadmin/saved:/saved:rw'
      - '/opt/docker/configs/phpmyadmin/upload:/upload:rw'
      - '/opt/docker/configs/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro'
      - '/opt/docker/configs/phpmyadmin/themes:/var/www/html/themes:ro'
    secrets:
      - 'MySQL-PW'
    networks:
      - 'mysql'
    deploy:
      mode: 'replicated'
      replicas: 1
      placement:
        constraints:
          - 'node.labels.Main == true'
      restart_policy:
        condition: 'any'
```
