### ISSUE TITLE
Custom themes not working in 5.2

### ISSUE THREAD

**Issue by ToshY** [phpmyadmin/docker#379]
**Problem**

Since phpMyAdmin `5.2` it doesn't seem possible to mount volume for a custom themes anymore. 

The documentation for [docker examples in the main repo](https://github.com/phpmyadmin/phpmyadmin/blob/master/doc/setup.rst#docker-examples) makes this even more confusing as mounting to `/www/themes` doesn't seem to have any effect, as where mounting to `/var/www/html/themes` worked for `5.1`.

**Reproduction**

1. Download a theme from [themes repo](https://github.com/phpmyadmin/themes), e.g. darkwolf.
2. Mount theme directory to `/www/themes`

```yaml
  pma:
    image: phpmyadmin:5.2
    security_opt:
      - no-new-privileges:true
    restart: always
    environment:
      DATABASE_ALLOW_NO_PASSWORD: 0
      PMA_HOST: ${DATABASE_HOST}
      PMA_PORT: ${DATABASE_PORT}
      HIDE_PHP_VERSION: 1
      PMA_ABSOLUTE_URI: "https://pma.example.local"
    networks:
      - proxy
    volumes:
      - pma_data:/sessions
      - ./docker/pma/themes/darkwolf:/www/themes/darkwolf
```

3. Take a look at the homepage

![image](https://user-images.githubusercontent.com/31921460/182219055-5dd50aca-5c23-44f2-a0ff-548d987cc73f.png)

Mounting to `/var/www/html/themes` doesn't show the new theme in `5.2` either.
