### ISSUE TITLE
config.user.inc.php not used

### ISSUE THREAD

**Issue by stanthewizzard** [phpmyadmin/docker#382]
Installed with compose

```
---
version: '3.7'
services:
  db:
    image: mariadb:latest
    container_name: phpmyadmin_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xxxxxxxxxxxxxxxx

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
         restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions
     - "./config/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php"
    restart: unless-stopped
```

config.user.inc.php:

```
<?php
$cfg['AllowArbitraryServer'] = true;

```

on the page no menu for the DB

if docker exec -it phpmyadmin /bin/bash
apt update
apt install vim

vi /etc/phpmyadmin/config.user.inc.php
this is the file from thje docker
thus 5.2.0 doesn't user config.user.inc.php
or am I doing it wrong ?

thank for help

**Comment by williamdes** [comment]
Hi @stanthewizzard
You should use the ENV `PMA_ARBITRARY`

Adding
```yml
- PMA_ARBITRARY=1
```

It should work and do what you wanted
To test if the file works fine you can make it "crash" by removing the `;`
If phpMyAdmin stops loading then we can conclude it was loaded and overridden somewhere 
I see nothing that would not allow the file to work except wrong permissions on the file

**Comment by stanthewizzard** [comment]
I added

```
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    ports:
     - 8080:80
    volumes:
     - /sessions
     - "./config/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php"
    restart: unless-stopped
```
and 

```
<?php
$cfg['AllowArbitraryServer'] = true
```

NO CRASH
config.user.inc.php is not used IMHO

Thanks
