### ISSUE TITLE
User not created in phpmyadmin when using docker-compose

### ISSUE THREAD

**Issue by sandwichdreams** [phpmyadmin/docker#392]
When I run `docker-compose up` the container starts and I can log in with root, but no user named _phpmyadmin_ is created. Is there something missing in the yml file?

```
version: "3.0"

networks:
    dev:

services:
  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mariadb
    restart: always
    ports:
      - "8080:80"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=phpmyadmin
      - MYSQL_PASSWORD=phpmyadmin
      - PMA_HOST=mariadb
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - dev
```
