### ISSUE TITLE
configuration storage broken

### ISSUE THREAD

**Issue by felixtech-msp** [phpmyadmin/docker#402]
When running the current Docker image with the following configuration I can select a server in the left sidebar and on every page there is a error "Ungültige Server-Nummer: 0". (Environment is all German)
Ale there is this error on the home page: "Der phpMyAdmin-Konfigurationsspeicher ist nicht vollständig konfiguriert, einige erweiterte Funktionen wurden deaktiviert."

This happens when newly creating the container instantly.

Also the content of the config.user.inc.php is completely ignored.

This has previously worked in the same configuration.
I can reproduce those errors on any server I try, even a freshly installed and updated server.

```yaml
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8306:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - PMA_USER=user
      - PMA_PASSWORD=secret
      - PMA_CONTROLHOST=pmadb
      - PMA_PMADB=pmadb
      - PMA_CONTROLUSER=pmadb
      - PMA_CONTROLPASS=secret
      - TZ=Europe/Berlin
    links:
      - database
      - pmadb
    depends_on:
      - database
      - pmadb
    volumes:
      - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
```

config.user.inc.php
```
<?php
$cfg['Servers'][$i]['hide_db'] = 'information_schema';
```
