### ISSUE TITLE
Connection refused from local database with custom port

### ISSUE THREAD

**Issue by biladina** [phpmyadmin/docker#429]
## Problem:
I have database connection from jumphost that forward to my local machine with custom port, so in the end it is local db connection with custom port..
the problem is, I can't login to the database from phpmyadmin, it says connection refused, `mysqli::real_connect(): (HY000/2002): Connection refused`
![index](https://github.com/phpmyadmin/docker/assets/10651085/ceabb45b-ce05-4b8e-ae9b-29b5ce10fc72)
I can login to mysql via console with command `mysql -h 127.0.0.1 -P 8001 -u root -p`, and also try login with app like DBeaver, it works, but can't login with phpmyadmin
![Screenshot_20230922_170702](https://github.com/phpmyadmin/docker/assets/10651085/34b0f2d7-8dbe-40af-9037-fa9abf52075e)

## Expected result:
can login and access the database

## Environment:
host: 127.0.0.1
port: 8001
MySQL version: 8.0.34

**docker-compose.yml**
```yml
version: '3.2'

services:
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    env_file:
      - variables.env

networks:
  default:
    name: nginx-proxy
    external: true
```

**variables.env**
```yml
PMA_HOSTS: 172.18.0.1,127.0.0.1
PMA_PORTS: 3306,8001
PMA_ABSOLUTE_URI: http://pma.lan
PMA_PMADB: phpmyadmin
MAX_EXECUTION_TIME: 2000
UPLOAD_LIMIT: 300M
HIDE_PHP_VERSION: true
```
