### ISSUE TITLE
Error 524 behind Cloudflare tunnel

### ISSUE THREAD

**Issue by music-db** [phpmyadmin/docker#459]
Trying to access phpMyAdmin behind Cloudflare cloudflared tunnel.
The login page shows up instantly, but it takes ages to log in. When the main page loads, you can't do anything; everything times out with error code 524.

here is my docker-compose.yml
```yaml
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: PhpMyAdmin
    restart: unless-stopped
    ports:
      - 8001:80
    environment:
      PMA_HOST: 192.168.2.11
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: https://pma.my-domain-name.com/
      UPLOAD_LIMIT: 100M
```
All Ajax (XHR) requests fail with error 524.
![Image](https://github.com/user-attachments/assets/e32a7dc5-16cb-4301-ae7e-255c181769d9)
